#!/bin/sh
# Script to run a flextesa Tezos sandbox
# https://tezos.gitlab.io/flextesa/

image=oxheadalpha/flextesa:latest
script=jakartabox
docker run --rm --name flextesa --detach -p 5432:5432 -e block_time=2 -e flextesa_node_cors_origin='*' "$image" "$script" start